name: Amazon Affiliate Bot Scheduler

on:
  schedule:
    # Morning slot: 10:12-10:20 AM IST (4:42-4:50 AM UTC)
    - cron: '42-50 4 * * *'
    # Afternoon slot: 1:12-1:20 PM IST (7:42-7:50 AM UTC)  
    - cron: '42-50 7 * * *'
    # Evening slot: 6:12-6:20 PM IST (12:42-12:50 PM UTC)
    - cron: '42-50 12 * * *'
    # Night slot: 9:12-9:20 PM IST (3:42-3:50 PM UTC)
    - cron: '42-50 15 * * *'
  
  # Manual trigger for testing
  workflow_dispatch:
    inputs:
      slot:
        description: 'Time slot to execute'
        required: true
        default: 'morning'
        type: choice
        options:
          - morning
          - afternoon
          - evening
          - night

jobs:
  determine-slot:
    runs-on: ubuntu-latest
    outputs:
      slot: ${{ steps.determine.outputs.slot }}
    steps:
      - name: Determine time slot
        id: determine
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "slot=${{ github.event.inputs.slot }}" >> $GITHUB_OUTPUT
          else
            # Determine slot based on current UTC time
            current_hour=$(date -u +%H)
            if [ $current_hour -eq 4 ]; then
              echo "slot=morning" >> $GITHUB_OUTPUT
            elif [ $current_hour -eq 7 ]; then
              echo "slot=afternoon" >> $GITHUB_OUTPUT
            elif [ $current_hour -eq 12 ]; then
              echo "slot=evening" >> $GITHUB_OUTPUT
            elif [ $current_hour -eq 15 ]; then
              echo "slot=night" >> $GITHUB_OUTPUT
            else
              echo "slot=morning" >> $GITHUB_OUTPUT
            fi
          fi

  send-links:
    needs: determine-slot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          cd bot
          pip install -r requirements.txt
          
      - name: Execute bot for time slot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          cd bot
          python scheduler_bot.py ${{ needs.determine-slot.outputs.slot }}
          
      - name: Commit and push progress
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git diff --staged --quiet || git commit -m "Update progress: ${{ needs.determine-slot.outputs.slot }} slot completed"
          git push

  send-status:
    needs: [determine-slot, send-links]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send status notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ADMIN_CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            🤖 Amazon Affiliate Bot Status
            
            ⏰ Slot: ${{ needs.determine-slot.outputs.slot }}
            📅 Time: ${{ github.run_id }}
            ✅ Status: ${{ needs.send-links.result }}
            
            Repository: ${{ github.repository }}
